### ISSUE TITLE
failing to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by matanster** [allenai/pdffigures#5]
This seems to be a great library. However although tested on Ubuntu 14.04 as per the readme, I fail to build it there. Perhaps someone can comment.

First, `libpoppler-dev` depends on `libtiff4`, which isn't there for Ubuntu 14.04 (found an old copy from a prior Ubuntu release to overcome this). Without this hack, `libpoppler-dev` would not install with `apt-get`.

Then, `g++ 4.9` resides on a test ppa of Ubuntu. So I ultimately added `ubuntu-toolchain-r/test` to apt to get it.

However I note that in my case no header files were installed by libpoppler-dev - in fact, none are listed as included in the deb package to begin with (as per http://packages.ubuntu.com/uk/trusty-updates/amd64/libpoppler-dev/filelist).

And so I obtained the headers directly from a poppler download and added them to the include path for the compiler, which ultimately results in the following error, after having altered the makefile to the 4.9 compiler (`CC=g++-4.9`). It is very likely though, that my makefile adaptations were not sufficient/correct.

```
$ make DEBUG=0
g++-4.9 -std=c++11 -c -Wall `pkg-config --cflags poppler` -I/usr/leptonica -g -O3 -c PDFUtils.cpp
PDFUtils.cpp: In constructor ‘SplashGraphicsOutputDev::SplashGraphicsOutputDev(SplashColorMode, int, GBool, SplashColorPtr, GBool, GBool, SplashThinLineMode, GBool)’:
PDFUtils.cpp:114:42: error: no matching function for call to ‘SplashOutputDev::SplashOutputDev(SplashColorMode&, int&, GBool&, Guchar*&, GBool&, GBool&, SplashThinLineMode&, GBool&)’
                         overprintPreviewA) {}
```

Perhaps someone can comment where I could have short-circuited this cascade for a more straightforward installation! Thanks!!

**Comment by domoritz** [comment]
This works fine for me:

```
sudo apt-get install libpoppler-dev libleptonica-dev pkg-config
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9
make DEBUG=0 CC='g++-4.9 -std=c++11'
```

**Comment by matanster** [comment]
Thanks @domoritz - it appears poppler-dev doesn't come with the included headers for Ubuntu 14.04, and I had to build poppler from source for them. Starting with a fresh pull of the repo and after all prerequisites have been installed already, I still get the compilation error that follows, when issuing `make DEBUG=0 CC='g++-4.9 -std=c++11`

```
$ make DEBUG=0 CC='g++-4.9 -std=c++11'
g++-4.9 -std=c++11 -c -Wall `pkg-config --cflags poppler` -I/usr/leptonica -g -O3 -c PDFUtils.cpp
PDFUtils.cpp: In constructor ‘SplashGraphicsOutputDev::SplashGraphicsOutputDev(SplashColorMode, int, GBool, SplashColorPtr, GBool, GBool, SplashThinLineMode, GBool)’:
PDFUtils.cpp:114:42: error: no matching function for call to ‘SplashOutputDev::SplashOutputDev(SplashColorMode&, int&, GBool&, Guchar*&, GBool&, GBool&, SplashThinLineMode&, GBool&)’
                         overprintPreviewA) {}
                                          ^
PDFUtils.cpp:114:42: note: candidates are:
In file included from PDFUtils.cpp:5:0:
/usr/local/include/poppler/SplashOutputDev.h:171:3: note: SplashOutputDev::SplashOutputDev(SplashColorMode, int, GBool, SplashColorPtr, GBool, SplashThinLineMode, GBool)
   SplashOutputDev(SplashColorMode colorModeA, int bitmapRowPadA,
   ^
/usr/local/include/poppler/SplashOutputDev.h:171:3: note:   candidate expects 7 arguments, 8 provided
/usr/local/include/poppler/SplashOutputDev.h:167:7: note: constexpr SplashOutputDev::SplashOutputDev(const SplashOutputDev&)
 class SplashOutputDev: public OutputDev {
       ^
/usr/local/include/poppler/SplashOutputDev.h:167:7: note:   candidate expects 1 argument, 8 provided
PDFUtils.cpp: In function ‘std::unique_ptr<Pix> getFullRenderPix(PDFDoc*, int, double)’:
PDFUtils.cpp:193:55: error: no matching function for call to ‘SplashOutputDev::SplashOutputDev(SplashColorMode, int, bool, SplashColor, bool, bool, SplashThinLineMode, bool)’
                           splashThinLineDefault, gTrue);
                                                       ^
PDFUtils.cpp:193:55: note: candidates are:
In file included from PDFUtils.cpp:5:0:
/usr/local/include/poppler/SplashOutputDev.h:171:3: note: SplashOutputDev::SplashOutputDev(SplashColorMode, int, GBool, SplashColorPtr, GBool, SplashThinLineMode, GBool)
   SplashOutputDev(SplashColorMode colorModeA, int bitmapRowPadA,
   ^
/usr/local/include/poppler/SplashOutputDev.h:171:3: note:   candidate expects 7 arguments, 8 provided
/usr/local/include/poppler/SplashOutputDev.h:167:7: note: constexpr SplashOutputDev::SplashOutputDev(const SplashOutputDev&)
 class SplashOutputDev: public OutputDev {
       ^
/usr/local/include/poppler/SplashOutputDev.h:167:7: note:   candidate expects 1 argument, 8 provided
make: *** [PDFUtils.o] Error 1
```

Does this look like I'm using an incompatible version of poppler?

**Comment by jenniferzhu** [comment]
I have the same issue... any ideas? @chrisc36 @matanster
