### ISSUE TITLE
Compile fault at PDFUtils

### ISSUE THREAD

**Issue by kungfujam** [allenai/pdffigures#9]
After having successfully compiled before I'm now hitting an issue running 

    make DEBUG=0

I'm running max 10.10.4 and have run 

    brew install poppler leptonica

Which installs versions leptonica/1.72 and poppler/0.34.0_1

Here is the error:
```
kungfujam$ make DEBUG=0
g++ -std=c++11 -c -Wall `pkg-config --cflags poppler lept` -g -O3 -c PDFUtils.cpp
PDFUtils.cpp:109:9: error: no matching constructor for initialization of
      'SplashOutputDev'
      : SplashOutputDev(colorModeA, bitmapRowPadA, reverseVideoA, paperColorA,
        ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/poppler/0.34.0_1/include/poppler/SplashOutputDev.h:171:3: note: 
      candidate constructor not viable: requires at most 7 arguments, but 8 were
      provided
  SplashOutputDev(SplashColorMode colorModeA, int bitmapRowPadA,
  ^
/usr/local/Cellar/poppler/0.34.0_1/include/poppler/SplashOutputDev.h:167:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 8 were provided
class SplashOutputDev: public OutputDev {
      ^
PDFUtils.cpp:189:11: error: no matching constructor for initialization of
      'SplashOutputDev'
      new SplashOutputDev(splashModeMono8, 4, gFalse, paperColor, gTrue, gTrue,
          ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/poppler/0.34.0_1/include/poppler/SplashOutputDev.h:171:3: note: 
      candidate constructor not viable: requires at most 7 arguments, but 8 were
      provided
  SplashOutputDev(SplashColorMode colorModeA, int bitmapRowPadA,
  ^
/usr/local/Cellar/poppler/0.34.0_1/include/poppler/SplashOutputDev.h:167:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 8 were provided
class SplashOutputDev: public OutputDev {
      ^
2 errors generated.
make: *** [PDFUtils.o] Error 1```

**Comment by chrisc36** [comment]
The current build works with poppler 0.29. My general policy has been to keep it up-to-date with brew, so I will upgrade the codebase to work with 0.34.0_1 when I get a chance

**Comment by chrisc36** [comment]
Should be closed by 32368857df81f75ba9a0ef03c195ae4c626d41f
